# Generated by Django 2.2.7 on 2019-11-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaborPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('preco_p', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço P')),
                ('preco_m', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço M')),
                ('preco_g', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço G')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Desconto')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('PEQUENA', 'PEQUENA'), ('MEDIA', 'MEDIA'), ('GRANDE', 'GRANDE')], max_length=10)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('sabores', models.ManyToManyField(blank=True, to='pizzas.SaborPizza')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.Venda')),
            ],
        ),
    ]
