# Generated by Django 2.2.7 on 2019-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_auto_20191114_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nome_cliente',
            field=models.CharField(default='Sem nome', max_length=255, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço de Entrega'),
        ),
    ]
