# Generated by Django 2.2.7 on 2019-11-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20191114_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('medida', models.CharField(max_length=10, verbose_name='Medida')),
                ('volume', models.FloatField(verbose_name='Volume da Bebida')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
